stakater-nordmart-inventory:
  application:
    deployment:
      image:
        repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-inventory
        tag: 0.0.28
      imagePullSecrets: binero-nexus-docker-config